import { App, PluginSettingTab, Setting } from 'obsidian';
import type IdeatrPlugin from './main';
import { LLMSettingsSection } from './settings/sections/LLMSettingsSection';
import { CloudAISettingsSection } from './settings/sections/CloudAISettingsSection';
// ===== MVP VERSION - EXTRA SETTINGS SECTIONS COMMENTED OUT =====
// Domain checking removed - functionality hidden
// import { DomainSettingsSection } from './settings/sections/DomainSettingsSection';
// import { WebSearchSettingsSection } from './settings/sections/WebSearchSettingsSection';
// import { NameVariantSettingsSection } from './settings/sections/NameVariantSettingsSection';
// import { ScaffoldSettingsSection } from './settings/sections/ScaffoldSettingsSection';
// import { ProjectElevationSettingsSection } from './settings/sections/ProjectElevationSettingsSection';
// import { TutorialSettingsSection } from './settings/sections/TutorialSettingsSection';
import { ErrorLoggingSettingsSection } from './settings/sections/ErrorLoggingSettingsSection';
import { FeedbackSettingsSection } from './settings/sections/FeedbackSettingsSection';
import { CaptureModalSettingsSection } from './settings/sections/CaptureModalSettingsSection';
import { createHelpIcon } from './utils/HelpIcon';

export interface IdeatrSettings {
    llmProvider: 'llama' | 'anthropic' | 'openai' | 'gemini' | 'groq' | 'openrouter' | 'custom' | 'none';
    llamaServerUrl: string; // Keep for backward compatibility or external server
    llamaBinaryPath: string;
    modelPath: string;
    llamaServerPort: number;
    concurrency: number;
    llmTimeout: number;
    autoClassify: boolean;

    // Domain checking settings
    enableDomainCheck: boolean;
    autoCheckDomains: boolean;
    enableProspectr: boolean; // Feature flag to show/hide domain checking service references
    prospectrUrl: string;
    domainCheckTimeout: number; // milliseconds

    // Web search settings
    enableWebSearch: boolean;
    autoSearchExistence: boolean;
    webSearchProvider: 'google' | 'duckduckgo' | 'none';
    googleSearchApiKey: string;
    googleSearchEngineId: string;
    webSearchTimeout: number; // milliseconds
    maxSearchResults: number; // 1-10, default 5

    // Name variant generation
    enableNameVariants: boolean;
    autoGenerateVariants: boolean; // Auto-generate on capture vs manual
    maxVariants: number; // 5-10, default 8
    useLLMForNameExtraction: boolean; // Use LLM for intelligent name extraction
    variantCacheMaxSize: number; // Maximum cache entries (0 = unlimited)
    variantCachePersist: boolean; // Persist cache to disk

    // Scaffold generation
    enableScaffolds: boolean;
    scaffoldDefaultAction: 'append' | 'new-note'; // Append to current or create new

    // Dashboard settings
    dashboardDefaultView: 'table' | 'graph' | 'inbox';
    dashboardItemsPerPage: number;
    dashboardAutoRefresh: boolean;
    dashboardPersistFilters: boolean; // Persist filter state across sessions

    // Clustering settings
    enableClustering: boolean;
    clusteringAlgorithm: 'hierarchical' | 'kmeans' | 'dbscan';
    maxClusters: number; // 0 = auto-determine
    clusterColorScheme: 'category' | 'age' | 'random';
    clusteringSimilarityThreshold: number; // 0-1, default 0.3

    // Resurfacing settings
    enableResurfacing: boolean;
    resurfacingThresholdDays: number; // Default 7
    resurfacingFrequency: 'daily' | 'weekly' | 'manual';
    resurfacingTime: string; // HH:MM format, if scheduled (e.g., "09:00")
    autoGenerateDigest: boolean; // Auto-generate on schedule (v2)
    digestIncludeSummary: boolean; // Include summary in digest
    digestMaxIdeas: number; // Max ideas per digest (0 = unlimited)

    // Project elevation settings
    enableElevation: boolean; // Enable project elevation feature
    elevationProjectsDirectory: string; // Directory for elevated projects (default: "Projects")
    elevationCreateDevraMetadata: boolean; // Create project metadata file on elevation (for future project management integration)
    elevationDefaultFolders: string; // Comma-separated list of default folders (e.g., "docs,notes,assets")

    // AI Model Management
    setupCompleted: boolean; // First-launch setup completed
    modelDownloaded: boolean; // Model has been downloaded
    keepModelLoaded: boolean; // Keep model loaded in memory
    preloadOnStartup: boolean; // Preload model on Obsidian startup
    localModel: 'phi-3.5-mini' | 'qwen-2.5-7b' | 'llama-3.1-8b' | 'llama-3.3-70b'; // Selected local AI model

    // Cloud AI
    preferCloud: boolean; // Prefer cloud AI over local
    cloudProvider: 'anthropic' | 'openai' | 'gemini' | 'groq' | 'openrouter' | 'custom' | 'custom-model' | 'none';
    cloudApiKeys: Record<'anthropic' | 'openai' | 'gemini' | 'groq' | 'openrouter', string>; // API keys per provider
    cloudApiKey?: string; // Legacy field for backward compatibility (deprecated)
    customEndpointUrl: string; // Custom endpoint URL (for self-hosted)
    openRouterModel: string; // OpenRouter model selection
    customModelProvider?: 'anthropic' | 'openai' | 'gemini' | 'groq'; // Provider for custom model selection
    customModel?: string; // Custom model ID for custom-model provider

    // File Organization
    moveArchivedToFolder: boolean; // Move archived ideas to Ideas/Archived/ directory

    // Error Logging (for bug reports)
    errorLoggingEnabled: boolean; // Enable error logging
    errorLogMaxEntries: number; // Maximum number of error log entries
    errorLogRetentionDays: number; // Days to retain error logs

    // Debug Mode (for developers)
    debugMode: boolean; // Enable debug logging (gates console.log/info/warn)

    // Capture Modal Keyboard Shortcuts
    captureIdeaHotkey: string; // Keyboard shortcut for opening Capture Idea modal (e.g., "cmd+i" or "ctrl+i")
    captureSaveShortcut: string; // Keyboard shortcut for Save button (e.g., "cmd+enter" or "ctrl+enter")
    captureIdeateShortcut: string; // Keyboard shortcut for Ideate button (e.g., "ctrl+enter" or "alt+enter")
}

export const DEFAULT_SETTINGS: IdeatrSettings = {
    llmProvider: 'llama',
    llamaServerUrl: 'http://127.0.0.1:8080',
    llamaBinaryPath: '',
    modelPath: '',
    llamaServerPort: 8080,
    concurrency: 1,
    llmTimeout: 10000, // Increased default for local inference
    autoClassify: true,

    // Domain checking
    enableDomainCheck: true,
    autoCheckDomains: false, // Manual by default (user can enable auto)
    enableProspectr: false, // Hidden by default until domain checking service is available
    prospectrUrl: 'http://localhost:3000',
    domainCheckTimeout: 10000, // 10 seconds

    // Web search
    enableWebSearch: true,
    autoSearchExistence: false, // Manual by default
    webSearchProvider: 'google',
    googleSearchApiKey: '',
    googleSearchEngineId: '',
    webSearchTimeout: 15000, // 15 seconds
    maxSearchResults: 5,

    // Name variant generation
    enableNameVariants: true,
    autoGenerateVariants: false, // Manual by default (user can enable auto)
    maxVariants: 8,
    useLLMForNameExtraction: false, // Rule-based by default (user can enable LLM)
    variantCacheMaxSize: 100, // Default: 100 entries
    variantCachePersist: true, // Persist cache by default

    // Scaffold generation
    enableScaffolds: true,
    scaffoldDefaultAction: 'append', // Append to current note by default

    // Dashboard
    dashboardDefaultView: 'table',
    dashboardItemsPerPage: 50,
    dashboardAutoRefresh: true,
    dashboardPersistFilters: true,

    // Clustering
    enableClustering: true,
    clusteringAlgorithm: 'hierarchical',
    maxClusters: 0, // Auto
    clusterColorScheme: 'category',
    clusteringSimilarityThreshold: 0.3,

    // Resurfacing
    enableResurfacing: true,
    resurfacingThresholdDays: 7,
    resurfacingFrequency: 'manual', // Manual for v1
    resurfacingTime: '09:00',
    autoGenerateDigest: false, // Manual for v1
    digestIncludeSummary: true,
    digestMaxIdeas: 0, // Unlimited

    // Project elevation
    enableElevation: true,
    elevationProjectsDirectory: 'Projects',
    elevationCreateDevraMetadata: true, // Create .devra.json metadata file (for future project management integration)
    elevationDefaultFolders: 'docs,notes,assets', // Default folders to create

    // AI Model Management
    setupCompleted: false,
    modelDownloaded: false,
    keepModelLoaded: false,
    preloadOnStartup: false,
    localModel: 'phi-3.5-mini',

    // Cloud AI
    preferCloud: false,
    cloudProvider: 'none',
    cloudApiKeys: {
        anthropic: '',
        openai: '',
        gemini: '',
        groq: '',
        openrouter: ''
    },
    customEndpointUrl: '',
    openRouterModel: '',
    customModelProvider: undefined,
    customModel: undefined,

    // File Organization
    moveArchivedToFolder: false, // Default: don't move files, just update status

    // Error Logging
    errorLoggingEnabled: true, // Default: enabled
    errorLogMaxEntries: 50, // Default: 50 entries
    errorLogRetentionDays: 7, // Default: 7 days

    // Debug Mode (for developers)
    debugMode: false, // Default: false (only enabled for developer vaults)

    // Capture Modal Keyboard Shortcuts
    captureIdeaHotkey: 'cmd+i', // Default: Cmd+I (Mac) or Ctrl+I (Windows/Linux) - users can customize
    captureSaveShortcut: 'alt+enter', // Default: Alt+Enter (Mac) or Alt+Enter (Windows/Linux) - users can customize
    captureIdeateShortcut: 'cmd+enter' // Default: Cmd+Enter (Mac) or Ctrl+Enter (Windows/Linux)
};

export class IdeatrSettingTab extends PluginSettingTab {
    plugin: IdeatrPlugin;

    constructor(app: App, plugin: IdeatrPlugin) {
        super(app, plugin);
        this.plugin = plugin;
    }

    display(): void {
        const { containerEl } = this;

        containerEl.empty();

        ;

        // Beta notice with Local AI version warning
        const betaNotice = containerEl.createDiv({ cls: 'ideatr-beta-notice' });
        (betaNotice as HTMLElement).setCssProps({
            'background': 'var(--background-modifier-border)',
            'padding': '1em',
            'border-radius': '4px',
            'margin-bottom': '1.5em',
            'border-left': '3px solid var(--text-warning)'
        });
        
        const betaTitle = betaNotice.createEl('strong', { text: '⚠️ local AI version - no updates' });
        (betaTitle).setCssProps({
            'display': 'block',
            'margin-bottom': '0.5em',
            'color': 'var(--text-warning)'
        });
        
        const betaText = betaNotice.createEl('p', { 
            text: 'This version (v0.8.6) includes local AI functionality but will not receive updates or bug fixes. This is a one-time snapshot release for users who want to try local AI in the Obsidian plugin.'
        });
        (betaText as HTMLElement).setCssProps({
            'margin': '0.5em 0',
            'line-height': '1.5'
        });
        
        const desktopAppText = betaNotice.createEl('p', {
            text: 'We recommend keeping an eye out for the upcoming ideatr desktop app, which will include local AI with ongoing support and updates.'
        });
        (desktopAppText as HTMLElement).setCssProps({
            'margin': '0.5em 0',
            'line-height': '1.5'
        });
        
        const desktopAppLink = betaNotice.createEl('a', {
            text: 'Learn more about desktop app →',
            href: 'https://ideatr.app/desktop',
            attr: { target: '_blank', rel: 'noopener' }
        });
        (desktopAppLink as HTMLElement).setCssProps({
            'color': 'var(--text-accent)',
            'text-decoration': 'none',
            'display': 'inline-block',
            'margin-top': '0.5em'
        });
        
        const betaActions = betaNotice.createDiv();
        (betaActions as HTMLElement).setCssProps({
            'margin-top': '0.75em',
            'display': 'flex',
            'gap': '0.5em',
            'flex-wrap': 'wrap'
        });
        
        const reportButton = betaActions.createEl('a', { 
            text: '📝 report bug or request a feature',
            href: '#ideatr-feedback-section'
        });
        (reportButton as HTMLElement).setCssProps({
            'color': 'var(--text-accent)',
            'text-decoration': 'none',
            'cursor': 'pointer'
        });
        reportButton.addEventListener('click', (e) => {
            e.preventDefault();
            // Scroll to feedback section after a short delay to ensure it's rendered
            setTimeout(() => {
                const feedbackSection = containerEl.querySelector('#ideatr-feedback-section');
                if (feedbackSection) {
                    feedbackSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            }, 100);
        });
        
        const roadmapLink = betaActions.createEl('a', { 
            text: '🗺️ view planned features',
            href: 'https://github.com/FallingWithStyle/obsidian-ideatr#roadmap',
            attr: { target: '_blank', rel: 'noopener' }
        });
        (roadmapLink as HTMLElement).setCssProps({
            'color': 'var(--text-accent)',
            'text-decoration': 'none'
        });
        
        const githubLink = betaActions.createEl('a', { 
            text: '🐛 GitHub issues',
            href: 'https://github.com/FallingWithStyle/obsidian-ideatr/issues',
            attr: { target: '_blank', rel: 'noopener' }
        });
        (githubLink as HTMLElement).setCssProps({
            'color': 'var(--text-accent)',
            'text-decoration': 'none'
        });

        // ===== MVP SETTINGS - CORE CAPTURE + AI ONLY =====
        // Initialize core sections only
        const llmSection = new LLMSettingsSection(this.app, this.plugin, this);
        const cloudAISection = new CloudAISettingsSection(this.app, this.plugin, this);
        const errorLoggingSection = new ErrorLoggingSettingsSection(this.app, this.plugin, this);
        const feedbackSection = new FeedbackSettingsSection(this.app, this.plugin, this);
        const captureModalSection = new CaptureModalSettingsSection(this.app, this.plugin, this);

        // Display core sections
        llmSection.display(containerEl);
        cloudAISection.display(containerEl);

        // Feedback Section
        const feedbackTitle = containerEl.createDiv({ cls: 'settings-section-title', attr: { id: 'ideatr-feedback-section' } });
        new Setting(feedbackTitle).setName('Feedback & support').setHeading();
        feedbackSection.display(containerEl);

        // Error Logging Settings
        new Setting(containerEl).setName('Error logging').setHeading();
        errorLoggingSection.display(containerEl);

        // Capture Modal Settings
        const captureTitle = containerEl.createDiv({ cls: 'settings-section-title' });
        new Setting(captureTitle).setName('Capture modal').setHeading();
        const captureHelpIcon = createHelpIcon(this.app, 'capture-workflows', 'Learn about Capture Modal');
        captureTitle.appendChild(captureHelpIcon);
        captureModalSection.display(containerEl);

        // ===== EXTRA SETTINGS DISABLED FOR MVP =====
        // The following settings sections are disabled to focus on core capture functionality:
        // - Validation Tools (web search, domain checking)
        // - Transformation Tools (name variants, scaffolds)
        // - Project Elevation
        // - Tutorials
        //
        // To re-enable these settings, uncomment the following sections:

        /*
        // Initialize extra sections
        const webSearchSection = new WebSearchSettingsSection(this.app, this.plugin, this);
        const nameVariantSection = new NameVariantSettingsSection(this.app, this.plugin, this);
        const scaffoldSection = new ScaffoldSettingsSection(this.app, this.plugin, this);
        const projectElevationSection = new ProjectElevationSettingsSection(this.app, this.plugin, this);
        const tutorialSection = new TutorialSettingsSection(this.app, this.plugin, this);

        // Validation Tools Section
        const validationTitle = containerEl.createDiv({ cls: 'settings-section-title' });
        new Setting(validationTitle).setName('Validation tools').setHeading();
        const validationHelpIcon = createHelpIcon(this.app, 'validation', 'Learn about Validation Tools');
        validationTitle.appendChild(validationHelpIcon);
        webSearchSection.display(containerEl);

        // Transformation Tools Section
        const transformationTitle = containerEl.createDiv({ cls: 'settings-section-title' });
        new Setting(transformationTitle).setName('Transformation tools').setHeading();
        const transformationHelpIcon = createHelpIcon(this.app, 'transformation', 'Learn about Transformation Tools');
        transformationTitle.appendChild(transformationHelpIcon);
        nameVariantSection.display(containerEl);
        scaffoldSection.display(containerEl);

        // Project Elevation Section
        projectElevationSection.display(containerEl);

        // Tutorial Settings
        tutorialSection.display(containerEl);
        */
    }
}
