import { App, PluginSettingTab, Setting } from 'obsidian';
import type IdeatrPlugin from './main';
// ===== MVP VERSION - CLOUD AI ONLY =====
// Local AI (LLMSettingsSection) has been removed
import { CloudAISettingsSection } from './settings/sections/CloudAISettingsSection';
// ===== EXTRA SETTINGS SECTIONS REMOVED FOR MVP =====
// Domain checking removed - functionality hidden
// import { DomainSettingsSection } from './settings/sections/DomainSettingsSection';
// import { WebSearchSettingsSection } from './settings/sections/WebSearchSettingsSection';
// import { NameVariantSettingsSection } from './settings/sections/NameVariantSettingsSection';
// import { ScaffoldSettingsSection } from './settings/sections/ScaffoldSettingsSection';
// import { ProjectElevationSettingsSection } from './settings/sections/ProjectElevationSettingsSection';
// import { TutorialSettingsSection } from './settings/sections/TutorialSettingsSection';
import { ErrorLoggingSettingsSection } from './settings/sections/ErrorLoggingSettingsSection';
import { FeedbackSettingsSection } from './settings/sections/FeedbackSettingsSection';
import { CaptureModalSettingsSection } from './settings/sections/CaptureModalSettingsSection';
import { createHelpIcon } from './utils/HelpIcon';

export interface IdeatrSettings {
    // ===== MVP: CLOUD AI ONLY =====
    // Local AI (llama) has been removed in MVP version
    
    llmTimeout: number;
    autoClassify: boolean;

    // Cloud AI (CORE MVP FEATURE)
    cloudProvider: 'anthropic' | 'openai' | 'gemini' | 'groq' | 'openrouter' | 'custom' | 'custom-model' | 'none';
    cloudApiKeys: Record<'anthropic' | 'openai' | 'gemini' | 'groq' | 'openrouter', string>; // API keys per provider
    customEndpointUrl: string; // Custom endpoint URL (for self-hosted)
    openRouterModel: string; // OpenRouter model selection
    customModelProvider?: 'anthropic' | 'openai' | 'gemini' | 'groq'; // Provider for custom model selection
    customModel?: string; // Custom model ID for custom-model provider

    // First-launch setup
    setupCompleted: boolean; // First-launch setup completed

    // Error Logging (for bug reports)
    errorLoggingEnabled: boolean; // Enable error logging
    errorLogMaxEntries: number; // Maximum number of error log entries
    errorLogRetentionDays: number; // Days to retain error logs

    // Debug Mode (for developers)
    debugMode: boolean; // Enable debug logging (gates console.log/info/warn)

    // Capture Modal Keyboard Shortcuts
    captureIdeaHotkey: string; // Keyboard shortcut for opening Capture Idea modal (e.g., "cmd+i" or "ctrl+i")
    captureSaveShortcut: string; // Keyboard shortcut for Save button (e.g., "cmd+enter" or "ctrl+enter")
    captureIdeateShortcut: string; // Keyboard shortcut for Ideate button (e.g., "ctrl+enter" or "alt+enter")

    // ===== EXTRA SETTINGS REMOVED FOR MVP =====
    // These settings are no longer used but kept for backward compatibility with existing vaults
    llmProvider?: 'llama' | 'anthropic' | 'openai' | 'gemini' | 'groq' | 'openrouter' | 'custom' | 'none';
    llamaServerUrl?: string;
    llamaBinaryPath?: string;
    modelPath?: string;
    llamaServerPort?: number;
    concurrency?: number;
    enableDomainCheck?: boolean;
    autoCheckDomains?: boolean;
    enableProspectr?: boolean;
    prospectrUrl?: string;
    domainCheckTimeout?: number;
    enableWebSearch?: boolean;
    autoSearchExistence?: boolean;
    webSearchProvider?: 'google' | 'duckduckgo' | 'none';
    googleSearchApiKey?: string;
    googleSearchEngineId?: string;
    webSearchTimeout?: number;
    maxSearchResults?: number;
    enableNameVariants?: boolean;
    autoGenerateVariants?: boolean;
    maxVariants?: number;
    useLLMForNameExtraction?: boolean;
    variantCacheMaxSize?: number;
    variantCachePersist?: boolean;
    enableScaffolds?: boolean;
    scaffoldDefaultAction?: 'append' | 'new-note';
    dashboardDefaultView?: 'table' | 'graph' | 'inbox';
    dashboardItemsPerPage?: number;
    dashboardAutoRefresh?: boolean;
    dashboardPersistFilters?: boolean;
    enableClustering?: boolean;
    clusteringAlgorithm?: 'hierarchical' | 'kmeans' | 'dbscan';
    maxClusters?: number;
    clusterColorScheme?: 'category' | 'age' | 'random';
    clusteringSimilarityThreshold?: number;
    enableResurfacing?: boolean;
    resurfacingThresholdDays?: number;
    resurfacingFrequency?: 'daily' | 'weekly' | 'manual';
    resurfacingTime?: string;
    autoGenerateDigest?: boolean;
    digestIncludeSummary?: boolean;
    digestMaxIdeas?: number;
    enableElevation?: boolean;
    elevationProjectsDirectory?: string;
    elevationCreateDevraMetadata?: boolean;
    elevationDefaultFolders?: string;
    modelDownloaded?: boolean;
    keepModelLoaded?: boolean;
    preloadOnStartup?: boolean;
    localModel?: 'phi-3.5-mini' | 'qwen-2.5-7b' | 'llama-3.1-8b' | 'llama-3.3-70b';
    preferCloud?: boolean;
    cloudApiKey?: string; // Legacy field
    moveArchivedToFolder?: boolean;
}

export const DEFAULT_SETTINGS: IdeatrSettings = {
    // ===== MVP: CLOUD AI ONLY =====
    llmTimeout: 30000, // 30 seconds for cloud API calls
    autoClassify: true,

    // Cloud AI (CORE MVP FEATURE)
    cloudProvider: 'none',
    cloudApiKeys: {
        anthropic: '',
        openai: '',
        gemini: '',
        groq: '',
        openrouter: ''
    },
    customEndpointUrl: '',
    openRouterModel: '',
    customModelProvider: undefined,
    customModel: undefined,

    // First-launch setup
    setupCompleted: false,

    // Error Logging
    errorLoggingEnabled: true,
    errorLogMaxEntries: 50,
    errorLogRetentionDays: 7,

    // Debug Mode
    debugMode: false,

    // Capture Modal Keyboard Shortcuts
    captureIdeaHotkey: 'cmd+i',
    captureSaveShortcut: 'alt+enter',
    captureIdeateShortcut: 'cmd+enter'
};

export class IdeatrSettingTab extends PluginSettingTab {
    plugin: IdeatrPlugin;

    constructor(app: App, plugin: IdeatrPlugin) {
        super(app, plugin);
        this.plugin = plugin;
    }

    display(): void {
        const { containerEl } = this;

        containerEl.empty();

        ;

        // MVP notice
        const mvpNotice = containerEl.createDiv({ cls: 'ideatr-mvp-notice' });
        (mvpNotice as HTMLElement).setCssProps({
            'background': 'var(--background-modifier-border)',
            'padding': '1em',
            'border-radius': '4px',
            'margin-bottom': '1.5em',
            'border-left': '3px solid var(--text-accent)'
        });
        
        const mvpTitle = mvpNotice.createEl('strong', { 
            text: 'Ideatr MVP - cloud AI only' 
        });
        (mvpTitle).setCssProps({
            'display': 'block',
            'margin-bottom': '0.5em',
            'color': 'var(--text-accent)'
        });
        
        const mvpText = mvpNotice.createEl('p', { 
            text: 'This version (v0.9.0-mvp) focuses on the core feature: fast idea capture with optional AI enhancement. Use supported cloud AI providers (Anthropic, OpenAI, Gemini, Groq, or OpenRouter) for best results. Additional features will be added soon, once core features are verified.'
        });
        (mvpText as HTMLElement).setCssProps({
            'margin': '0.5em 0',
            'line-height': '1.5'
        });
        
        const mvpActions = mvpNotice.createDiv();
        (mvpActions as HTMLElement).setCssProps({
            'margin-top': '0.75em',
            'display': 'flex',
            'gap': '0.5em',
            'flex-wrap': 'wrap'
        });
        
        const reportButton = mvpActions.createEl('a', { 
            text: '📝 Report bug or request a feature',
            href: '#ideatr-feedback-section'
        });
        (reportButton as HTMLElement).setCssProps({
            'color': 'var(--text-accent)',
            'text-decoration': 'none',
            'cursor': 'pointer'
        });
        reportButton.addEventListener('click', (e) => {
            e.preventDefault();
            // Scroll to feedback section after a short delay to ensure it's rendered
            setTimeout(() => {
                const feedbackSection = containerEl.querySelector('#ideatr-feedback-section');
                if (feedbackSection) {
                    feedbackSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            }, 100);
        });
        
        const githubLink = mvpActions.createEl('a', { 
            text: '🐛 GitHub issues',
            href: 'https://github.com/FallingWithStyle/obsidian-ideatr/issues',
            attr: { target: '_blank', rel: 'noopener' }
        });
        (githubLink as HTMLElement).setCssProps({
            'color': 'var(--text-accent)',
            'text-decoration': 'none'
        });

        // ===== MVP SETTINGS - CLOUD AI ONLY =====
        // Initialize core sections only (local AI removed)
        const cloudAISection = new CloudAISettingsSection(this.app, this.plugin, this);
        const errorLoggingSection = new ErrorLoggingSettingsSection(this.app, this.plugin, this);
        const feedbackSection = new FeedbackSettingsSection(this.app, this.plugin, this);
        const captureModalSection = new CaptureModalSettingsSection(this.app, this.plugin, this);

        // Display cloud AI settings
        cloudAISection.display(containerEl);

        // Feedback Section
        const feedbackTitle = containerEl.createDiv({ cls: 'settings-section-title', attr: { id: 'ideatr-feedback-section' } });
        new Setting(feedbackTitle).setName('Feedback & support').setHeading();
        feedbackSection.display(containerEl);

        // Error Logging Settings
        new Setting(containerEl).setName('Error logging').setHeading();
        errorLoggingSection.display(containerEl);

        // Capture Modal Settings
        const captureTitle = containerEl.createDiv({ cls: 'settings-section-title' });
        new Setting(captureTitle).setName('Capture modal').setHeading();
        const captureHelpIcon = createHelpIcon(this.app, 'capture-workflows', 'Learn about Capture Modal');
        captureTitle.appendChild(captureHelpIcon);
        captureModalSection.display(containerEl);

        // ===== EXTRA SETTINGS DISABLED FOR MVP =====
        // The following settings sections are disabled to focus on core capture functionality:
        // - Validation Tools (web search, domain checking)
        // - Transformation Tools (name variants, scaffolds)
        // - Project Elevation
        // - Tutorials
        //
        // To re-enable these settings, uncomment the following sections:

        /*
        // Initialize extra sections
        const webSearchSection = new WebSearchSettingsSection(this.app, this.plugin, this);
        const nameVariantSection = new NameVariantSettingsSection(this.app, this.plugin, this);
        const scaffoldSection = new ScaffoldSettingsSection(this.app, this.plugin, this);
        const projectElevationSection = new ProjectElevationSettingsSection(this.app, this.plugin, this);
        const tutorialSection = new TutorialSettingsSection(this.app, this.plugin, this);

        // Validation Tools Section
        const validationTitle = containerEl.createDiv({ cls: 'settings-section-title' });
        new Setting(validationTitle).setName('Validation tools').setHeading();
        const validationHelpIcon = createHelpIcon(this.app, 'validation', 'Learn about Validation Tools');
        validationTitle.appendChild(validationHelpIcon);
        webSearchSection.display(containerEl);

        // Transformation Tools Section
        const transformationTitle = containerEl.createDiv({ cls: 'settings-section-title' });
        new Setting(transformationTitle).setName('Transformation tools').setHeading();
        const transformationHelpIcon = createHelpIcon(this.app, 'transformation', 'Learn about Transformation Tools');
        transformationTitle.appendChild(transformationHelpIcon);
        nameVariantSection.display(containerEl);
        scaffoldSection.display(containerEl);

        // Project Elevation Section
        projectElevationSection.display(containerEl);

        // Tutorial Settings
        tutorialSection.display(containerEl);
        */
    }
}
